// Generated by CoPilot
package com.ecommerce.orderprocessing.exception;

/**
 * Thrown when attempting to create or update a customer with an email that already exists.
 */
public class CustomerEmailAlreadyExistsException extends RuntimeException {

    public CustomerEmailAlreadyExistsException(String customer_email) {
        super("Customer email already exists: " + customer_email);
    }
}

